import { existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { writeFileAtomic } from './atomic-write.js'
import { piAgentDir } from './paths.js'
import { step, tilde } from './ui.js'

/** pi has no settings-file hooks; its extension point is a TypeScript file
 *  auto-discovered from `<agent-dir>/extensions/*.ts`. So the pi guard is a
 *  generated file rather than a settings entry, with the same lifecycle as the
 *  Claude hook: written by `login` (which self-update re-runs, refreshing the
 *  baked binary path), removed by `uninstall`, skipped by USAGEFLEET_HOOK=0. */
const FILE = 'usagefleet-guard.ts'

export function piGuardPath(agentDir: string = piAgentDir()): string {
	return join(agentDir, 'extensions', FILE)
}

/** The generated extension is self-contained on purpose — it shells out to the
 *  baked `usagefleet guard` command instead of importing this package, so a CLI
 *  update can never strand it against moved internals. Program and config are
 *  baked exactly like guardCommand does for the Claude hook. */
export function piGuardExtension(program: string[], configPath?: string): string {
	const env = configPath ? `{ ...process.env, USAGEFLEET_CONFIG: ${JSON.stringify(configPath)} }` : 'process.env'
	return `// Generated by \`usagefleet login\` — do not edit; \`usagefleet uninstall\` removes it,
// USAGEFLEET_HOOK=0 at login keeps it out. Refuses pi prompts while this
// device's group has blocking enabled and is over its budget, mirroring the
// Claude Code UserPromptSubmit hook.
import { execFile } from 'node:child_process'

const GUARD = ${JSON.stringify(program)}
const ENV = ${env}

/** Exit 2 is guard's one "refuse this prompt" signal, stderr the reason meant
 *  for the user. Anything else — exit 0, a missing binary, a wedged process
 *  killed by the timeout — fails open, the same guarantee \`usagefleet guard\`
 *  itself makes. The 7s outer bound only covers a wedged process; guard's own
 *  fetch gives up at 5s. */
function runGuard(): Promise<string | null> {
	return new Promise(resolve => {
		execFile(GUARD[0], GUARD.slice(1), { env: ENV, timeout: 7000 }, (error, _out, stderr) => {
			const code = error === null ? 0 : error.code
			resolve(code === 2 ? stderr.trim() || 'usagefleet: prompts are blocked for this group.' : null)
		})
	})
}

type InputEvent = { source?: string }
type InputContext = { hasUI: boolean; ui: { notify(message: string, level: 'error'): void } }
type InputHandler = (event: InputEvent, ctx: InputContext) => Promise<{ action: 'handled' } | undefined>

export default function (pi: { on(event: 'input', handler: InputHandler): void }) {
	pi.on('input', async (event, ctx) => {
		// Extension-injected messages pass unguarded: silently swallowing one
		// wedges the extension that sent it, and the human this block is aimed
		// at is the one typing.
		if (event.source === 'extension') {
			return undefined
		}
		const blocked = await runGuard()
		if (!blocked) {
			return undefined
		}
		if (ctx.hasUI) {
			ctx.ui.notify(blocked, 'error')
		} else {
			console.error(blocked)
		}
		return { action: 'handled' }
	})
}
`
}

/** Skips machines without pi (agent dir absent) rather than conjuring a `.pi`
 *  tree that pi itself never made. */
export function installPiGuard(program: string[], agentDir: string = piAgentDir()): void {
	if (process.env.USAGEFLEET_HOOK === '0' || !existsSync(agentDir)) {
		return
	}
	const path = piGuardPath(agentDir)
	const next = piGuardExtension(program, process.env.USAGEFLEET_CONFIG)
	let current = ''
	try {
		current = readFileSync(path, 'utf-8')
	} catch {
		/* not installed yet */
	}
	if (current === next) {
		return
	}
	mkdirSync(dirname(path), { recursive: true })
	writeFileAtomic(path, next)
	console.log(step('hook', `pi prompt guard · ${tilde(path)}`))
}

export function uninstallPiGuard(agentDir: string = piAgentDir()): void {
	const path = piGuardPath(agentDir)
	if (!existsSync(path)) {
		return
	}
	rmSync(path, { force: true })
	console.log(step('removed', `pi prompt guard · ${tilde(path)}`))
}
